### ISSUE TITLE
[Team member]: Matthieu Muffato

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/pipelines-website#12]
### Full Name

Matthieu Muffato

### Team

Informatics Infrastructure (ToL–IT)

### Job Title

Team Lead

### Role description

Matthieu leads the Informatics Infrastructure team, which guides the implementation and delivery of the genome assembly pipelines, and provides support for large-scale genome analyses for the Tree of Life faculty teams.

He joined the Wellcome Sanger Institute in February 2021, to form the Informatics Infrastructure team for the Tree of Life programme. He has recruited 7 team members, with skills covering data curation & management, software development & operations, and bioinformatics.

### Which pipelines have you contributed towards?

- [X] blobtoolkit
- [X] ensemblgenedownload
- [X] ensemblrepeatdownload
- [X] genomeassembly
- [X] genomenote
- [X] insdcdownload
- [X] readmapping
- [X] sequencecomposition
- [X] treeval
- [X] variantcalling

### GitHub

@muffato

### Sanger Page

https://www.sanger.ac.uk/person/muffato-matthieu/

### LinkedIn

https://www.linkedin.com/in/matthieu-muffato/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanka-surana** [comment]
@muffato This is copied from your Sanger page, but please feel free to make any changes.

**Comment by muffato** [comment]
All good, thank you !

**Comment by priyanka-surana** [comment]
Bio added.
