### ISSUE TITLE
[Team]: Informatics Infrastructure

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/pipelines-website#13]
### Team

Informatics Infrastructure (ToL–IT)

### Short description

The Informatics Infrastructure team provides support for the production of reference genome assemblies and large-scale genome analyses in the Tree of Life programme, and helps with the management and use of the institute's IT resources.

### Long description

The Tree of Life projects will generate tens of thousands of high-quality genomes – more than have ever been sequenced! It is a challenging and extremely exciting task that will shape the future of biology, and the team’s role is to provide the platform for assembling and analysing those genomes at an unprecedented scale. We are the interface between the Tree of Life teams (assembly production and faculty research) and Sanger IT, working together with the informatics teams of the other programmes.

The team is organised in three poles.

**Data management**

Our data curators and managers maintain the integrity, consistency, and quality, or multiple databases used in production, including [Genomes on a Tree (GoaT)](https://goat.genomehubs.org/), [Sample Tracking System (STS)](https://sangerinstitute.blog/2022/12/08/software-to-sort-samples-and-sequence-species-at-scale/), [Collaborative Open Plant Omics (COPO)](https://copo-project.org/), and [BioSamples](https://www.ebi.ac.uk/biosamples/).

**Bioinformatics**

Our bioinformaticians develop the [suite of analysis pipelines](https://pipelines.tol.sanger.ac.uk/pipelines) that will run on every genome produced in Tree of Life, providing a central database of core results available for all.

**Systems**

We develop and maintain some core systems used in production, including the execution and tracking of all bioinformatics pipelines, and the deployment of third-party web applications for internal use.

### Tech stack

The team uses a wide range of technologies, frameworks and programming languages, including Nextflow, Python, Conda, Jira, LSF, Singularity, and Kubernetes. The technology wheel below shows most of their logos. How many can you recognise?

[tech stack image](https://www.sanger.ac.uk/wp-content/uploads/Informatics-Infrastructure-Technology-wheel-300.png)
[Informatics Infrastructure Technology wheel.pdf](https://github.com/sanger-tol/pipelines-website/files/11778388/Informatics.Infrastructure.Technology.wheel.pdf)
![Informatics Infrastructure Technology wheel.svg](https://github.com/sanger-tol/pipelines-website/assets/623458/0973980b-a827-408d-a99b-94436b5235b4)

### Current Members

Priyanka Surana (@priyanka-surana)
Matthieu Muffato (@muffato)
Beth Yates (@BethYates)
Cibele Sotero-Caio (@)
Cibin Sadasivan Baby (@cibinsb)
Guoying Qi (@gq1)
Paul Davis (@)

### Which pipelines has the team contributed towards?

- [X] blobtoolkit
- [X] ensemblgenedownload
- [X] ensemblrepeatdownload
- [X] genomeassembly
- [X] genomenote
- [X] insdcdownload
- [X] readmapping
- [X] sequencecomposition
- [X] treeval
- [X] variantcalling

### Any additional information

This is currently identical to our FRED page. Everyone please update with current relevant information. Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muffato** [comment]
I have updated the content to match the [page on Fred](https://fred.wellcomegenomecampus.org/page/5655?utm_source=interact&utm_medium=side_menu_category) (and asked Luke to push the content of the Fred page to the Sanger website)

**Comment by priyanka-surana** [comment]
1. Updating "IDS resources" in short description to "informatics resources and digital solutions", since external audience will have no idea what IDS stands for.
2. Updating "IDS" in long description to "Informatics and Digital Solutions team at the Wellcome Sanger Institute".
3. Similarly for STS, is there a link to a landing/description page? The current link just takes the visitor to the login page and our visitors will not have access. I am removing the link for now, and keep looking for an alternative.
4. Updating link for "suite of analysis pipelines" to https://pipelines.tol.sanger.ac.uk/pipelines
5. Can you share a copy of the tech stack image in png/svg format?

**Comment by muffato** [comment]
1. Done
2. Done
3. For STS, the best description I could find is https://sangerinstitute.blog/2022/12/08/software-to-sort-samples-and-sequence-species-at-scale/
4. Done

**Comment by priyanka-surana** [comment]
Team description added.
