### ISSUE TITLE
[Team member]: Paul

### ISSUE THREAD

**Issue by Paul-Davis** [sanger-tol/pipelines-website#21]
### Full Name

Paul Davis

### Team

Informatics Infrastructure (ToL–IT)

### Job Title

Data Manager

### Role description

Paul works on the main ToL Genome Engine. This system was developed by the ToL to manage and track samples from collection, onboarding, processing in the lab, sequencing and finally the publication of the assembly and Genome Note publication. As there are many steps in this process developing methodology to identify issues as early as possible is vital to avoid wasted time and resource. Paul works at all levels of the project fielding questions about data flow, data fixes and helps other ToL staff and project stakeholders with data and information. Paul also interacts with external groups and stakeholders to maintain data integrity in the public domain.

### GitHub

https://github.com/Paul-Davis

### Sanger Page

https://www.sanger.ac.uk/person/davis-paul/

### Twitter

@SirPaulDavis

### LinkedIn

https://www.linkedin.com/in/paul-davis-uk/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanka-surana** [comment]
Bio added. Thanks for submitting.
