### ISSUE TITLE
[Team member]: 

### ISSUE THREAD

**Issue by BethYates** [sanger-tol/pipelines-website#26]
### Full Name

Beth Yates

### Team

Informatics Infrastructure (ToL–IT)

### Job Title

Bioinformatics Engineer

### Role description

Beth is a Bioinformatics Engineer working on a building a platform to automate the production of [Genome Note publications](https://wellcomeopenresearch.org/gateways/treeoflife). The Universal Genome Note platform consists of a web portal, database and Nextflow pipelines. Beth is contributing to the genomenote pipeline, this pipeline fetches assembly meta data and generates some of the figures and statistics included in each genome note. 

### GitHub

https://github.com/BethYates

### LinkedIn

https://www.linkedin.com/in/bethanyates/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanka-surana** [comment]
Added ✅
