### ISSUE TITLE
[Project]: Genome Note Portal

### ISSUE THREAD

**Issue by BethYates** [sanger-tol/pipelines-website#27]
### Are you adding a project, poster or presentation?

Project

### Team

Informatics Infrastructure (ToL–IT)

### Project Name or Poster/Presentation Title

Genome Notes Portal

### Link to the project, poster or presentation

https://notes.tol.sanger.ac.uk/

### Short description

The Genome Notes portal is being developed to automate the production of [Genome Note publications](https://wellcomeopenresearch.org/gateways/treeoflife). It will consist of a React UI, Python API, Postgres database and will run Nextflow data pipelines to generate some of the required images and statistics contained within a genome note. The platform is being designed to have the ability to produce genome note style publications for both Tree of Life assemblies and genome assemblies sequenced elsewhere.

### Which programming languages and/or technologies were used?

React, SQLAlchemy, Alembic, Postgres, Python, Nextflow

### Which team members contributed

@BethYates
@sanger-tol/platforms 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanka-surana** [comment]
Do we list both SQLAlchemy and Alembic? Is Alembic not part of SQLAlchemy?

**Comment by BethYates** [comment]
That all looks good to me, leaving out alembic is fine too.
